//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class Transactions
    {
        [DataMember]
        public int Transaction_ID { get; set; }
        [DataMember]
        public Nullable<int> Product_ID { get; set; }
        [DataMember]
        public System.DateTime Date { get; set; }
        [DataMember]
        public decimal Amount_Paid { get; set; }
        [DataMember]
        public Nullable<int> Card_Number { get; set; }
        [DataMember]
        public Nullable<int> EMI_Tenure { get; set; }

        public virtual EMICard EMICard { get; set; }
        public virtual Products Products { get; set; }
    }
}